window.esdocSearchIndex = [
  [
    "jira-client/src/jira.js~jiraapi",
    "class/src/jira.js~JiraApi.html",
    "<span>JiraApi</span> <span class=\"search-result-import-path\">jira-client/src/jira.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/jira.js",
    "file/src/jira.js.html",
    "src/jira.js",
    "file"
  ],
  [
    "src/jira.js~jiraapi#addattachmentonissue",
    "class/src/jira.js~JiraApi.html#instance-method-addAttachmentOnIssue",
    "src/jira.js~JiraApi#addAttachmentOnIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addcomment",
    "class/src/jira.js~JiraApi.html#instance-method-addComment",
    "src/jira.js~JiraApi#addComment",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addissuetosprint",
    "class/src/jira.js~JiraApi.html#instance-method-addIssueToSprint",
    "src/jira.js~JiraApi#addIssueToSprint",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addnewcomponent",
    "class/src/jira.js~JiraApi.html#instance-method-addNewComponent",
    "src/jira.js~JiraApi#addNewComponent",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addnewissue",
    "class/src/jira.js~JiraApi.html#instance-method-addNewIssue",
    "src/jira.js~JiraApi#addNewIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addwatcher",
    "class/src/jira.js~JiraApi.html#instance-method-addWatcher",
    "src/jira.js~JiraApi#addWatcher",
    "method"
  ],
  [
    "src/jira.js~jiraapi#addworklog",
    "class/src/jira.js~JiraApi.html#instance-method-addWorklog",
    "src/jira.js~JiraApi#addWorklog",
    "method"
  ],
  [
    "src/jira.js~jiraapi#apiversion",
    "class/src/jira.js~JiraApi.html#instance-member-apiVersion",
    "src/jira.js~JiraApi#apiVersion",
    "member"
  ],
  [
    "src/jira.js~jiraapi#base",
    "class/src/jira.js~JiraApi.html#instance-member-base",
    "src/jira.js~JiraApi#base",
    "member"
  ],
  [
    "src/jira.js~jiraapi#baseoptions",
    "class/src/jira.js~JiraApi.html#instance-member-baseOptions",
    "src/jira.js~JiraApi#baseOptions",
    "member"
  ],
  [
    "src/jira.js~jiraapi#constructor",
    "class/src/jira.js~JiraApi.html#instance-constructor-constructor",
    "src/jira.js~JiraApi#constructor",
    "method"
  ],
  [
    "src/jira.js~jiraapi#createproject",
    "class/src/jira.js~JiraApi.html#instance-method-createProject",
    "src/jira.js~JiraApi#createProject",
    "method"
  ],
  [
    "src/jira.js~jiraapi#createremotelink",
    "class/src/jira.js~JiraApi.html#instance-method-createRemoteLink",
    "src/jira.js~JiraApi#createRemoteLink",
    "method"
  ],
  [
    "src/jira.js~jiraapi#createversion",
    "class/src/jira.js~JiraApi.html#instance-method-createVersion",
    "src/jira.js~JiraApi#createVersion",
    "method"
  ],
  [
    "src/jira.js~jiraapi#deletecomponent",
    "class/src/jira.js~JiraApi.html#instance-method-deleteComponent",
    "src/jira.js~JiraApi#deleteComponent",
    "method"
  ],
  [
    "src/jira.js~jiraapi#deleteissue",
    "class/src/jira.js~JiraApi.html#instance-method-deleteIssue",
    "src/jira.js~JiraApi#deleteIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#deleteversion",
    "class/src/jira.js~JiraApi.html#instance-method-deleteVersion",
    "src/jira.js~JiraApi#deleteVersion",
    "method"
  ],
  [
    "src/jira.js~jiraapi#deletewebhook",
    "class/src/jira.js~JiraApi.html#instance-method-deleteWebhook",
    "src/jira.js~JiraApi#deleteWebhook",
    "method"
  ],
  [
    "src/jira.js~jiraapi#deleteworklog",
    "class/src/jira.js~JiraApi.html#instance-method-deleteWorklog",
    "src/jira.js~JiraApi#deleteWorklog",
    "method"
  ],
  [
    "src/jira.js~jiraapi#dorequest",
    "class/src/jira.js~JiraApi.html#instance-method-doRequest",
    "src/jira.js~JiraApi#doRequest",
    "method"
  ],
  [
    "src/jira.js~jiraapi#findissue",
    "class/src/jira.js~JiraApi.html#instance-method-findIssue",
    "src/jira.js~JiraApi#findIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#findrapidview",
    "class/src/jira.js~JiraApi.html#instance-method-findRapidView",
    "src/jira.js~JiraApi#findRapidView",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getbacklogforrapidview",
    "class/src/jira.js~JiraApi.html#instance-method-getBacklogForRapidView",
    "src/jira.js~JiraApi#getBacklogForRapidView",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getcurrentuser",
    "class/src/jira.js~JiraApi.html#instance-method-getCurrentUser",
    "src/jira.js~JiraApi#getCurrentUser",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getlastsprintforrapidview",
    "class/src/jira.js~JiraApi.html#instance-method-getLastSprintForRapidView",
    "src/jira.js~JiraApi#getLastSprintForRapidView",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getproject",
    "class/src/jira.js~JiraApi.html#instance-method-getProject",
    "src/jira.js~JiraApi#getProject",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getremotelinks",
    "class/src/jira.js~JiraApi.html#instance-method-getRemoteLinks",
    "src/jira.js~JiraApi#getRemoteLinks",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getsprintissues",
    "class/src/jira.js~JiraApi.html#instance-method-getSprintIssues",
    "src/jira.js~JiraApi#getSprintIssues",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getunresolvedissuecount",
    "class/src/jira.js~JiraApi.html#instance-method-getUnresolvedIssueCount",
    "src/jira.js~JiraApi#getUnresolvedIssueCount",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getusersingroup",
    "class/src/jira.js~JiraApi.html#instance-method-getUsersInGroup",
    "src/jira.js~JiraApi#getUsersInGroup",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getusersissues",
    "class/src/jira.js~JiraApi.html#instance-method-getUsersIssues",
    "src/jira.js~JiraApi#getUsersIssues",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getversions",
    "class/src/jira.js~JiraApi.html#instance-method-getVersions",
    "src/jira.js~JiraApi#getVersions",
    "method"
  ],
  [
    "src/jira.js~jiraapi#getwebhook",
    "class/src/jira.js~JiraApi.html#instance-method-getWebhook",
    "src/jira.js~JiraApi#getWebhook",
    "method"
  ],
  [
    "src/jira.js~jiraapi#greenhopperversion",
    "class/src/jira.js~JiraApi.html#instance-member-greenhopperVersion",
    "src/jira.js~JiraApi#greenhopperVersion",
    "member"
  ],
  [
    "src/jira.js~jiraapi#host",
    "class/src/jira.js~JiraApi.html#instance-member-host",
    "src/jira.js~JiraApi#host",
    "member"
  ],
  [
    "src/jira.js~jiraapi#issuelink",
    "class/src/jira.js~JiraApi.html#instance-method-issueLink",
    "src/jira.js~JiraApi#issueLink",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listcomponents",
    "class/src/jira.js~JiraApi.html#instance-method-listComponents",
    "src/jira.js~JiraApi#listComponents",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listfields",
    "class/src/jira.js~JiraApi.html#instance-method-listFields",
    "src/jira.js~JiraApi#listFields",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listissuetypes",
    "class/src/jira.js~JiraApi.html#instance-method-listIssueTypes",
    "src/jira.js~JiraApi#listIssueTypes",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listpriorities",
    "class/src/jira.js~JiraApi.html#instance-method-listPriorities",
    "src/jira.js~JiraApi#listPriorities",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listprojects",
    "class/src/jira.js~JiraApi.html#instance-method-listProjects",
    "src/jira.js~JiraApi#listProjects",
    "method"
  ],
  [
    "src/jira.js~jiraapi#liststatus",
    "class/src/jira.js~JiraApi.html#instance-method-listStatus",
    "src/jira.js~JiraApi#listStatus",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listtransitions",
    "class/src/jira.js~JiraApi.html#instance-method-listTransitions",
    "src/jira.js~JiraApi#listTransitions",
    "method"
  ],
  [
    "src/jira.js~jiraapi#listwebhooks",
    "class/src/jira.js~JiraApi.html#instance-method-listWebhooks",
    "src/jira.js~JiraApi#listWebhooks",
    "method"
  ],
  [
    "src/jira.js~jiraapi#makerequestheader",
    "class/src/jira.js~JiraApi.html#instance-method-makeRequestHeader",
    "src/jira.js~JiraApi#makeRequestHeader",
    "method"
  ],
  [
    "src/jira.js~jiraapi#makesprintqueryuri",
    "class/src/jira.js~JiraApi.html#instance-method-makeSprintQueryUri",
    "src/jira.js~JiraApi#makeSprintQueryUri",
    "method"
  ],
  [
    "src/jira.js~jiraapi#makeuri",
    "class/src/jira.js~JiraApi.html#instance-method-makeUri",
    "src/jira.js~JiraApi#makeUri",
    "method"
  ],
  [
    "src/jira.js~jiraapi#makewebhookuri",
    "class/src/jira.js~JiraApi.html#instance-method-makeWebhookUri",
    "src/jira.js~JiraApi#makeWebhookUri",
    "method"
  ],
  [
    "src/jira.js~jiraapi#port",
    "class/src/jira.js~JiraApi.html#instance-member-port",
    "src/jira.js~JiraApi#port",
    "member"
  ],
  [
    "src/jira.js~jiraapi#protocol",
    "class/src/jira.js~JiraApi.html#instance-member-protocol",
    "src/jira.js~JiraApi#protocol",
    "member"
  ],
  [
    "src/jira.js~jiraapi#registerwebhook",
    "class/src/jira.js~JiraApi.html#instance-method-registerWebhook",
    "src/jira.js~JiraApi#registerWebhook",
    "method"
  ],
  [
    "src/jira.js~jiraapi#request",
    "class/src/jira.js~JiraApi.html#instance-member-request",
    "src/jira.js~JiraApi#request",
    "member"
  ],
  [
    "src/jira.js~jiraapi#searchjira",
    "class/src/jira.js~JiraApi.html#instance-method-searchJira",
    "src/jira.js~JiraApi#searchJira",
    "method"
  ],
  [
    "src/jira.js~jiraapi#searchusers",
    "class/src/jira.js~JiraApi.html#instance-method-searchUsers",
    "src/jira.js~JiraApi#searchUsers",
    "method"
  ],
  [
    "src/jira.js~jiraapi#strictssl",
    "class/src/jira.js~JiraApi.html#instance-member-strictSSL",
    "src/jira.js~JiraApi#strictSSL",
    "member"
  ],
  [
    "src/jira.js~jiraapi#transitionissue",
    "class/src/jira.js~JiraApi.html#instance-method-transitionIssue",
    "src/jira.js~JiraApi#transitionIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#updateissue",
    "class/src/jira.js~JiraApi.html#instance-method-updateIssue",
    "src/jira.js~JiraApi#updateIssue",
    "method"
  ],
  [
    "src/jira.js~jiraapi#updateversion",
    "class/src/jira.js~JiraApi.html#instance-method-updateVersion",
    "src/jira.js~JiraApi#updateVersion",
    "method"
  ],
  [
    "src/jira.js~jiraapi#webhookversion",
    "class/src/jira.js~JiraApi.html#instance-member-webhookVersion",
    "src/jira.js~JiraApi#webhookVersion",
    "member"
  ],
  [
    "src/jira.js~jiraapi.jiraapioptions",
    "typedef/index.html#static-typedef-JiraApiOptions",
    "src/jira.js~JiraApi.JiraApiOptions",
    "typedef"
  ],
  [
    "src/jira.js~jiraapi.oauth",
    "typedef/index.html#static-typedef-OAuth",
    "src/jira.js~JiraApi.OAuth",
    "typedef"
  ],
  [
    "src/jira.js~jiraapi.searchuseroptions",
    "typedef/index.html#static-typedef-SearchUserOptions",
    "src/jira.js~JiraApi.SearchUserOptions",
    "typedef"
  ],
  [
    "src/jira.js~jiraapi.makerequestheaderoptions",
    "typedef/index.html#static-typedef-makeRequestHeaderOptions",
    "src/jira.js~JiraApi.makeRequestHeaderOptions",
    "typedef"
  ]
]